In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('HpriceData.csv')

In [3]:
df

Area  Bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [4]:
import math
med = math.floor(df['Bedrooms'].median())
med

3

In [5]:
df['Bedrooms'].fillna(med, inplace=True)

In [6]:
X = df.drop('Price',axis=1)

In [7]:
X

Area  Bedrooms  Age
0  2600       3.0   20
1  3000       4.0   15
2  3200       3.0   18
3  3600       3.0   30
4  4000       5.0    8

In [10]:
Y = df['Price']

In [12]:
X.insert(0,'X0',[1,1,1,1,1])

In [13]:
X

X0  Area  Bedrooms  Age
0   1  2600       3.0   20
1   1  3000       4.0   15
2   1  3200       3.0   18
3   1  3600       3.0   30
4   1  4000       5.0    8

In [14]:
xtrans = X.T

In [15]:
xtrans

0       1       2       3       4
X0           1.0     1.0     1.0     1.0     1.0
Area      2600.0  3000.0  3200.0  3600.0  4000.0
Bedrooms     3.0     4.0     3.0     3.0     5.0
Age         20.0    15.0    18.0    30.0     8.0

In [16]:
xtransx = xtrans.dot(X)

In [17]:
import numpy as np

In [18]:
xtransxinv = np.linalg.inv(xtransx)

In [19]:
xtransxinv

array([[ 2.90831875e+01,  1.14437500e-03, -6.00493750e+00,
        -6.05437500e-01],
       [ 1.14437500e-03,  2.06875000e-06, -1.61187500e-03,
        -1.16875000e-04],
       [-6.00493750e+00, -1.61187500e-03,  2.22568750e+00,
         1.80187500e-01],
       [-6.05437500e-01, -1.16875000e-04,  1.80187500e-01,
         1.86875000e-02]])

In [20]:
xx = xtransxinv.dot(xtrans)

In [21]:
bteeta = xx.dot(Y)

In [23]:
(np.linalg.inv(((X.T).dot(X))).dot(X.T)).dot(Y)

array([ 3.83725e+05,  1.37250e+02, -2.60250e+04, -6.82500e+03])

In [22]:
bteeta

array([ 3.83725e+05,  1.37250e+02, -2.60250e+04, -6.82500e+03])

In [24]:
B0 = bteeta[0]
B1 = bteeta[1]
B2 = bteeta[2]
B3 = bteeta[3]

In [25]:
x1 = int(input("x1"))
x2 = int(input("x2"))
x3 = int(input("x3"))

x13000
x23
x340


In [26]:
Y = B0 + B1*x1 + B2*x2 + B3*x3

In [27]:
Y

444400.0000000029