In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('mydata.csv')

In [3]:
df

Y  X1  X2  X3
0  43  30  63  33
1  63  45  47  52
2  71  68  67  62
3  61  46  83  42
4  81  66  84  42
5  43  36  50  66

In [4]:
X = df.drop("Y",axis=1)

In [5]:
X

X1  X2  X3
0  30  63  33
1  45  47  52
2  68  67  62
3  46  83  42
4  66  84  42
5  36  50  66

In [6]:
Y = df["Y"]

In [7]:
Y

0    43
1    63
2    71
3    61
4    81
5    43
Name: Y, dtype: int64

In [8]:
X.insert(0,'X0',[1,1,1,1,1,1])

In [9]:
X

X0  X1  X2  X3
0   1  30  63  33
1   1  45  47  52
2   1  68  67  62
3   1  46  83  42
4   1  66  84  42
5   1  36  50  66

In [10]:
xtrans = X.T

In [11]:
xtrans

0   1   2   3   4   5
X0   1   1   1   1   1   1
X1  30  45  68  46  66  36
X2  63  47  67  83  84  50
X3  33  52  62  42  42  66

In [14]:
xtransx = xtrans.dot(X)

In [15]:
import numpy as np

In [16]:
xtransxinv = np.linalg.inv(xtransx)

In [17]:
xtransxinv

array([[ 1.69580230e+01,  8.31914459e-02, -1.73130574e-01,
        -1.91055228e-01],
       [ 8.31914459e-02,  1.89410821e-03, -1.54994977e-03,
        -1.48031635e-03],
       [-1.73130574e-01, -1.54994977e-03,  2.35593088e-03,
         1.89084867e-03],
       [-1.91055228e-01, -1.48031635e-03,  1.89084867e-03,
         2.80171396e-03]])

In [18]:
xx = xtransxinv.dot(xtrans)

In [19]:
bteeta = xx.dot(Y)

In [20]:
(np.linalg.inv(((X.T).dot(X))).dot(X.T)).dot(Y)

array([38.8730967 ,  1.06294938, -0.15180574, -0.40655013])

In [21]:
bteeta

array([38.8730967 ,  1.06294938, -0.15180574, -0.40655013])

In [22]:
B0 = bteeta[0]
B1 = bteeta[1]
B2 = bteeta[2]
B3 = bteeta[3]

In [23]:
x1 = int(input("x1"))
x2 = int(input("x2"))
x3 = int(input("x3"))

x139
x259
x369


In [24]:
Y = B0 + B1*x1 + B2*x2 + B3*x3

In [25]:
Y

43.319625064028756